# Generated by Django 4.0.3 on 2022-03-11 18:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_userprofile_address_userprofile_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='userskills',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 11, 18, 57, 53, 113746, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userskills',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='skill',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_cv', to='task.skillcv'),
        ),
    ]
