# Generated by Django 4.0.3 on 2022-03-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_skillcv_userskills_time_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
