# Generated by Django 4.0.3 on 2022-03-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_delete_userprofile_delete_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_cv', to='task.skillcv'),
        ),
    ]
